### PR TITLE
Adds documentation for output port sampling

### PR DESCRIPTION
**Pull request by sherm1**
An attempt at precise documentation for discrete update in the presence (and absence) of output port sampling.

Currently this is just a block in the MultibodyPlant class documentation for discussion. There will be some other changes needed once we settle on this part.

I'll paste the formatted doxygen below.

### CODE REVIEW

**Comment by sherm1** [comment]
image

**Comment by jwnimmer-tri** [comment]
Do you want us to review here, or merge this and then review on the other PR?  For my part, I'm happy to just dump this as-is into my branch and debate on the other page.

**Comment by sherm1** [comment]
Merging would be fine -- there are no conflicts at all since this is just a new section. That would make review easier since there is no Reviewable button here!

**Comment by sherm1** [comment]
cc @RussTedrake @amcastro-tri

**Comment by jwnimmer-tri** [comment]
I'll merge in a moment.  We'll review in the other PR, so don't start here yet!

**Comment by jwnimmer-tri** [comment]
Merged.

**Pull request closed without merging**
