### PR TITLE
add explicit negative test

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
https://github.com/robotlocomotion/drake/pull/18109

- - -
This change is [Reviewable](https://reviewable.io/reviews/jwnimmer-tri/drake/11)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
@jwnimmer-tri would you be up for incl. this in your pr?

**Comment by EricCousineau-TRI** [comment]
I think the only missing point here was that it simulates a missing binding, whether it be via missing import or a missing binding (perhaps in same module).

**Comment by EricCousineau-TRI** [comment]
But yeah, the ultimate side effect is captured in your PR - thanks!

**Comment by jwnimmer-tri** [comment]
A missing binding is a compilation failure (no type_caster).

**Comment by EricCousineau-TRI** [comment]
I think a2a977822a shows an effectively missing binding. It compiles:
```
$ bazel run //bindings/pydrake/common:py/serialize_pybind_test
```

However, per logic in PR, this defaults to `type_caster_generic`, thus can compile, but will fail at import time.
Am I missing something?

**Comment by jwnimmer-tri** [comment]
Ah.  _Some_ types fail at compile-time (maybe only templated types?), but I suppose some might fail at load-time.

So whether the type is unbound, or bound-but-not-yet-imported, we will experience an import failure.

Are you OK with only the existing unit test as sufficient?  It checks that an bound-but-unimported type is an import failure.  I'll posit that unbound-and-thus-unimported is covered sufficiently well by the existing test.

**Comment by EricCousineau-TRI** [comment]
yup yup, existing test works for me! I think the only note is that if we end up rolling into single module, we should keep that test and/or retarget it to represent a missing binding.

**Pull request closed without merging**
